### ISSUE TITLE
can you upload the code to receive the data?

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [wrybread/weewx-ArduinoWeatherStation#2]
hi, can you upload the code to receive the data to show on that page?

http://rproductions.org/wind

how did you do that?

thanks.

**Comment by wrybread** [comment]
Whoops, looks like that page is broken, here's a working version:

http://sinkingsensation.com/wind/

You can see the javascripts there, let me know if you need the PHP code that receives it. I think I packed it in the github release, let me know if not.

Make sure to look here:

https://github.com/wrybread/Weather-Underground-Style-Real-Time-Gauge

**Comment by openbooknoobdeveloper** [comment]
really thanks for the reply, I am very noob on this I will try do from scratch no experience with arduino at all.

I checked you haven't made any release of the project.

can't find the php file as well.

anyway I will be arround annoying you ok?

this project it is very important to me.

thanks you, have a nice weekend.
